# Generated by Django 5.0.1 on 2024-01-12 14:34

import communites.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to=communites.helper.upload_to),
        ),
    ]
