# Generated by Django 5.0.1 on 2024-01-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communites', '0002_alter_community_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='display_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
