# Generated by Django 5.0.1 on 2024-01-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communites', '0004_alter_postimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_quiz',
        ),
    ]
