# Generated by Django 5.0.1 on 2024-01-26 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communites', '0005_remove_posts_is_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='posts',
        ),
        migrations.AddField(
            model_name='posts',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communites.community'),
        ),
    ]
