# Generated by Django 5.0.1 on 2024-02-09 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('super_size', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyBlocks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ToolsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PictureChoiceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.picturechoice')),
            ],
        ),
        migrations.AddField(
            model_name='picturechoice',
            name='images',
            field=models.ManyToManyField(to='surveys.picturechoiceimages'),
        ),
        migrations.CreateModel(
            name='ShortText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_character', models.PositiveIntegerField(default=100)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='RedirectWithUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings_length', models.PositiveIntegerField(default=5)),
                ('alphabetical_order', models.BooleanField(default=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.AddField(
            model_name='picturechoice',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks'),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(max_length=30)),
                ('country_code', models.CharField(max_length=5)),
                ('number_domain', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('min', models.PositiveIntegerField(blank=True, null=True)),
                ('max', models.PositiveIntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='LongText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_character', models.PositiveIntegerField(default=100)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='EndScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.BooleanField(default=True)),
                ('button_link', models.URLField()),
                ('message', models.CharField(max_length=500)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_email', models.BooleanField(default=False)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='DropDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(max_length=100)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seperator', models.TextField(choices=[('-', '-'), ('.', '.'), ('/', '/')], default='/', max_length=30)),
                ('format', models.TextField(choices=[('yy_mm_dd', 'yy_mm_dd'), ('dd_mm_yy', 'dd_mm_yy'), ('mm_yy_dd', 'mm_yy_dd')], default='dd_mm_yy', max_length=30)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple_selection', models.BooleanField(default=True)),
                ('vertical_alignment', models.BooleanField(default=False)),
                ('randomize', models.BooleanField(default=False)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyBlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.TextField(choices=[('ConatctInfo', 'ContactInfo'), ('Email', 'Email'), ('PhoneNumber', 'PhoneNumber'), ('Website', 'Website'), ('Choices', 'Choices'), ('Dropdown', 'Dropdown'), ('PictureChoice', 'PictureChoice'), ('YesNo', 'YesNo'), ('Rating', 'Rating'), ('LongText', 'LongText'), ('ShortText', 'ShortText'), ('Time', 'Time'), ('Date', 'Date'), ('Number', 'Number'), ('QuestionGroup', 'QuestionGroup'), ('EndScreen', 'EndScreen'), ('RedirectToURL', 'RedirectToURL'), ('WelcomeScreen', 'WelcomeScreen')], default='ShortText')),
                ('is_required', models.BooleanField(default=False)),
                ('question', models.TextField(max_length=200)),
                ('number', models.PositiveIntegerField(default=1)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=250)),
                ('status', models.TextField(choices=[('DEVELOPMENT', 'DEVELOPMENT'), ('PRODUCTION', 'PRODUCTION')], default='DEVELOPMENT', max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='surveyblocks',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.CreateModel(
            name='SurveySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telphone_number', to='surveys.phonenumber')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_block', to='surveys.toolssettings')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='surveys.toolssettings')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_address_block', to='surveys.toolssettings')),
                ('first_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_name', to='surveys.toolssettings')),
                ('last_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_name', to='surveys.toolssettings')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
                ('address_line_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_one', to='surveys.toolssettings')),
                ('address_line_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_two', to='surveys.toolssettings')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='surveys.toolssettings')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='surveys.toolssettings')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='surveys.toolssettings')),
                ('zip_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zip_code', to='surveys.toolssettings')),
            ],
        ),
        migrations.CreateModel(
            name='UserReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('start_time', models.DateField(auto_now_add=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('response', models.CharField(max_length=2000)),
                ('browser_type', models.TextField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_url_with', models.TextField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
        migrations.CreateModel(
            name='YesNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks')),
            ],
        ),
    ]
