# Generated by Django 5.0.1 on 2024-02-10 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyblocks',
            name='title',
        ),
        migrations.RemoveField(
            model_name='surveyblocktype',
            name='question',
        ),
        migrations.AddField(
            model_name='surveysettings',
            name='show_progress_bar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surveysettings',
            name='show_question_number',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(choices=[('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('YELLOW', 'YELLOW')], default='GREEN', max_length=10)),
                ('font_size', models.TextField(choices=[('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('LARGE', 'LARGE')], default='MEDIUM', max_length=10)),
                ('background_img', models.URLField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
        ),
    ]
