# Generated by Django 5.0.1 on 2024-02-10 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_surveyblocks_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreponse',
            name='block',
        ),
        migrations.AddField(
            model_name='surveyblocks',
            name='question',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userreponse',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
    ]
