# Generated by Django 5.0.1 on 2024-02-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_userreponse_block_surveyblocks_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreponse',
            name='survey',
        ),
        migrations.AddField(
            model_name='userreponse',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocks'),
        ),
    ]
