# Generated by Django 5.0.1 on 2024-02-11 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_welcomescreen_have_continue_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='longtext',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='number',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='welcomescreen',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='picturechoice',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='date',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='endscreen',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='email',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='surveyblocktype',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='userreponse',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='website',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='yesno',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='redirectwithurl',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='shorttext',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys'),
        ),
        migrations.AddField(
            model_name='surveyblocktype',
            name='question',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='surveyblocktype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SurveyBlocks',
        ),
    ]
