# Generated by Django 5.0.1 on 2024-02-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_contactinfo_block_alter_longtext_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyblocktype',
            name='number',
        ),
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='choices',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='date',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dropdown',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='email',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='endscreen',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='longtext',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='number',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='picturechoice',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rating',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='redirectwithurl',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shorttext',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='website',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='welcomescreen',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='yesno',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
