# Generated by Django 5.0.1 on 2024-02-12 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_remove_dropdown_option_alter_userreponse_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='date',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='email',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='endscreen',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='longtext',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='number',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='picturechoice',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='redirectwithurl',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='shorttext',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='website',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='welcomescreen',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
        migrations.AlterField(
            model_name='yesno',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype'),
        ),
    ]
