# Generated by Django 5.0.1 on 2024-02-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_remove_address_block_remove_choices_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyblocktype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyblocktype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
