# Generated by Django 5.0.1 on 2024-02-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_surveyblocktype_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endscreen',
            old_name='button',
            new_name='have_button',
        ),
        migrations.AddField(
            model_name='endscreen',
            name='label',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='welcomescreen',
            name='button_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='welcomescreen',
            name='label',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
