# Generated by Django 5.0.1 on 2024-02-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_rename_button_endscreen_have_button_endscreen_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomescreen',
            name='background_image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='welcomescreen',
            name='custom_html',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
