# Generated by Django 5.0.1 on 2024-02-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_welcomescreen_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=50, null=True)),
                ('background_image', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='welcomescreen',
            name='time_to_complete',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_address', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='choices',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_choices', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_contact', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='date',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_data', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='dropdown',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_dropdown', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='email',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_email', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='endscreen',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_end', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='longtext',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_longtext', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='number',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_number', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_phonenumber', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='picturechoice',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_picture', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='rating',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_rating', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='redirectwithurl',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_redirect_with_url', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='shorttext',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_shorttext', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='website',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_website', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='welcomescreen',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_welcome', to='surveys.background'),
        ),
        migrations.AddField(
            model_name='yesno',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_yesno', to='surveys.background'),
        ),
    ]
