# Generated by Django 5.0.1 on 2024-02-21 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_background_welcomescreen_time_to_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtext',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.toolssettings'),
        ),
        migrations.AddField(
            model_name='shorttext',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.toolssettings'),
        ),
    ]
