# Generated by Django 5.0.1 on 2024-02-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_longtext_settings_shorttext_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='alphabetical_order',
        ),
    ]
