# Generated by Django 5.0.1 on 2024-02-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_remove_rating_alphabetical_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='number_of_submissions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='surveys',
            name='time_to_complete',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
