# Generated by Django 5.0.1 on 2024-02-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_remove_surveys_number_of_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveys',
            name='time_to_complete',
        ),
        migrations.AddField(
            model_name='surveys',
            name='show_number_of_submissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveys',
            name='show_time_to_complete',
            field=models.BooleanField(default=False),
        ),
    ]
