# Generated by Django 5.0.1 on 2024-02-27 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_surveyblocktype_phone_num_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumberCountries',
        ),
        migrations.RemoveField(
            model_name='surveyblocktype',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='surveyblocktype',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_number_blocks', to='surveys.phonenumber'),
        ),
        migrations.AlterField(
            model_name='surveyblocktype',
            name='picture_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_choice_blocks', to='surveys.picturechoice'),
        ),
    ]
