# Generated by Django 5.0.1 on 2024-02-27 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_delete_phonenumbercountries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.BooleanField(default=False)),
                ('format_number', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='yesno',
            name='label',
        ),
        migrations.AddField(
            model_name='yesno',
            name='allow_reselect',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='surveyblocktype',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_number_blocks', to='surveys.phonenumbers'),
        ),
    ]
