# Generated by Django 5.0.1 on 2024-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_surveyblocktype_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtext',
            name='place_holder',
            field=models.CharField(default='PlaceHolder', max_length=500),
        ),
        migrations.AddField(
            model_name='shorttext',
            name='place_holder',
            field=models.CharField(default='PlaceHolder', max_length=500),
        ),
    ]
