# Generated by Django 5.0.1 on 2024-02-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0031_longtext_place_holder_shorttext_place_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumbers',
            name='placeholder',
            field=models.CharField(default='Placeholder', max_length=500),
        ),
    ]
