# Generated by Django 5.0.1 on 2024-03-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0033_alter_date_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='format',
            field=models.TextField(choices=[('yyyy_MM_dd', 'yyyy_MM_dd'), ('dd_MM_yyyy', 'dd_MM_yyyy'), ('MM_yyyy_dd', 'MM_yyyy_dd'), ('PPP', 'PPP')], default='dd_MM_yyyy', max_length=30),
        ),
    ]
