# Generated by Django 5.0.1 on 2024-03-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0034_alter_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='format',
            field=models.TextField(choices=[('yyyy-MM-dd', 'yyyy-MM-dd'), ('dd-MM-yyyy', 'dd-MM-yyyy'), ('MM-yyyy-dd', 'MM-yyyy-dd'), ('PPP', 'PPP')], default='dd-MM-yyyy', max_length=30),
        ),
    ]
