# Generated by Django 5.0.1 on 2024-03-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0037_dropdown_allow_search_dropdown_alphabetically_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyblocktype',
            name='block_type',
            field=models.TextField(choices=[('ConatctInfo', 'ContactInfo'), ('Email', 'Email'), ('PhoneNumber', 'PhoneNumber'), ('Website', 'Website'), ('Choices', 'Choices'), ('DropDown', 'DropDown'), ('PictureChoice', 'PictureChoice'), ('YesNo', 'YesNo'), ('Rating', 'Rating'), ('LongText', 'LongText'), ('ShortText', 'ShortText'), ('Time', 'Time'), ('Date', 'Date'), ('Number', 'Number'), ('QuestionGroup', 'QuestionGroup'), ('EndScreen', 'EndScreen'), ('RedirectToURL', 'RedirectToURL'), ('WelcomeScreen', 'WelcomeScreen')], default='ShortText'),
        ),
    ]
