# Generated by Django 5.0.1 on 2024-03-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0038_alter_surveyblocktype_block_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picturechoiceimages',
            old_name='belongs_to',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='picturechoice',
            name='images',
        ),
    ]
