# Generated by Django 5.0.1 on 2024-03-16 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0039_rename_belongs_to_picturechoiceimages_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturechoice',
            name='multiple_selection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='picturechoiceimages',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='picturechoiceimages',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
