# Generated by Django 5.0.1 on 2024-03-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0040_picturechoice_multiple_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturechoiceimages',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
