# Generated by Django 5.0.1 on 2024-03-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0042_picturechoiceimages_blur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturechoiceimages',
            name='rotationIndex',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picturechoiceimages',
            name='x',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='picturechoiceimages',
            name='y',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
