# Generated by Django 5.0.1 on 2024-03-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0043_picturechoiceimages_rotationindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturechoiceimages',
            name='grayscale',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picturechoiceimages',
            name='hue',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='picturechoiceimages',
            name='pixelate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
