# Generated by Django 5.0.1 on 2024-03-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0044_picturechoiceimages_grayscale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirectwithurl',
            old_name='label',
            new_name='message',
        ),
        migrations.AddField(
            model_name='redirectwithurl',
            name='click_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='redirectwithurl',
            name='custom_html',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
