# Generated by Django 5.0.1 on 2024-03-21 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0046_redirectwithurl_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
