# Generated by Django 5.0.1 on 2024-01-09 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_emailverification_expires_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='booleanOption',
            new_name='answer_is_true',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 21, 20, 8, 513981, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 21, 5, 8, 513981, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='expires_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 21, 20, 8, 512984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 20, 55, 38, 513981, tzinfo=datetime.timezone.utc)),
        ),
    ]
