# Generated by Django 5.0.1 on 2024-01-11 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_booleanoption_question_answer_is_true_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 22, 25, 30, 794714, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 22, 10, 30, 794714, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='expires_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 22, 25, 30, 794714, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 22, 1, 0, 794714, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='descriptions',
            field=models.TextField(default='Nothing to see', max_length=2000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='instructions',
            field=models.TextField(default='Nothing to see', max_length=3000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='requirements',
            field=models.TextField(default='Nothing to see', max_length=2000),
        ),
    ]
