# Generated by Django 5.0.1 on 2024-01-12 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_emailverification_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='body',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 14, 39, 9, 553815, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 14, 24, 9, 553815, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='expires_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 14, 39, 9, 553815, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 14, 14, 39, 553815, tzinfo=datetime.timezone.utc)),
        ),
    ]
