# Generated by Django 5.0.1 on 2024-01-30 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_emailverification_expires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='type',
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('default', 'DEFAULT'), ('community_request', 'COMMUNITY_REQUEST'), ('new_quiz_alert', 'NEW_QUIZ_ALERT'), ('achievement', 'ACHIEVEMENT')], default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='notifications',
            name='path',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 12, 41, 27, 149836, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 12, 26, 27, 149836, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='expires_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 12, 41, 27, 149836, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 12, 16, 57, 149836, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
