# Generated by Django 5.0.1 on 2024-01-30 20:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_emailverification_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='quiz_banner',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user_requesting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_requesting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 20, 41, 54, 526176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 20, 26, 54, 526176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='expires_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 20, 41, 54, 526176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 20, 17, 24, 526176, tzinfo=datetime.timezone.utc)),
        ),
    ]
