# Generated by Django 5.0.1 on 2024-01-30 20:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_notifications_quiz_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='quiz_banner',
        ),
        migrations.AddField(
            model_name='notifications',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='base.quiz'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 21, 24, 20, 666448, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 21, 9, 20, 666448, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='expires_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 21, 24, 20, 665447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 20, 59, 50, 666448, tzinfo=datetime.timezone.utc)),
        ),
    ]
